### PR TITLE
Changes to generating washing machine shapes.

### PR DESCRIPTION
**Pull request by Smcg13**
These changes have not yet been tested with a midi device attached. Everything should work as no midi code has been changed, only changes to the gui and physics.

### CODE REVIEW

**Comment by Smcg13** [comment]
I just noticed that I also made some changes to the ball file. It now transmits on channel 1 and holds for 100ms. These were just for testing my set up and should be easy to change, the old ball file would also still work in its place.

**Comment by teesloane** [comment]
Thanks @Smcg13 ! I'm going to merge these in tonight. Really appreciate your input.

**Comment by Smcg13** [comment]
No, problem, it was fun. I just added on last thing on my fork before I go to bed. A drop down of available outputs to switch between. I've not tested it much but it works with my setup using external synths, not sure how it would work with soft synths.

**Comment by teesloane** [comment]
Woah! fantastic! I think you may need to submit another pull request based on your fork, since I've already merged the previous changes.

**Comment by teesloane** [comment]
@Smcg13 I just realized that I had to create a new development branch after I merged into master, so if you run into trouble submitting a pull request, you may have to reconfigure your git origin (although I can't remember how forks work on github; worse comes to worst, you might have to refork, but that shouldn't be the case). Let me know if you have any problems.

**Pull request merged**
